[package]
name = "uniwork-escrow"
version = "0.1.0"
description = "Escrow do Uni.work: trava o pagamento ate a confirmacao, com disputa, mediacao e liberacao por prazo"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "uniwork_escrow"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
